package uk.gov.digital.ho.hocs.audit.core;

public enum LogEvent {

    AUDIT_EVENT_CREATED,
    AUDIT_EVENT_DELETED,
    AUDIT_EVENT_CREATION_FAILED,
    AUDIT_RECORD_NOT_FOUND,
    CSV_CUSTOM_CONVERTER_FAILURE,
    CSV_EXPORT_COMPLETE,
    CSV_EXPORT_FAILURE,
    CSV_EXPORT_START,
    CSV_RECORD_EXPORT_FAILURE,
    INVALID_AUDIT_PAYLOAD_STORED,
    INVALID_CASE_TYPE_SPECIFIED,
    INVALID_PARAMETER_SPECIFIED,
    JSON_PARSE_EXCEPTION,
    MISSING_REQUEST_PARAMETER,
    NON_EXISTENT_VARIABLE,
    REFRESH_MATERIALISED_VIEW,
    REST_CLIENT_EXCEPTION,
    UNAUTHORISED_ACCESS,
    UNCAUGHT_EXCEPTION;

    public static final String EVENT = "event_id";
    public static final String EXCEPTION = "exception";

}
