package uk.gov.digital.ho.hocs.audit.core;

public enum LogEvent {
    AUDIT_EVENT_DELETED,
    AUDIT_EVENT_CREATION_FAILED,
    CSV_CUSTOM_CONVERTER_FAILURE,
    CSV_EXPORT_COMPLETE,
    CSV_EXPORT_START,
    INVALID_CASE_TYPE_SPECIFIED,
    INVALID_PARAMETER_SPECIFIED,
    JSON_PARSE_EXCEPTION,
    MISSING_REQUEST_PARAMETER,
    NON_EXISTENT_VARIABLE,
    REFRESH_MATERIALISED_VIEW,
    UNCAUGHT_EXCEPTION,
    USER_ROW_EXPORT_FAILURE,
    USER_EXPORT_FAILURE,
    UNIT_TEAM_EXPORT_FAILURE,
    UNIT_TEAM_UNIT_ROW_EXPORT_FAILURE,
    UNIT_TEAM_TEAM_ROW_EXPORT_FAILURE,
    TOPIC_EXPORT_FAILURE,
    TOPIC_ROW_EXPORT_FAILURE,
    TEAM_EXPORT_FAILURE,
    TEAM_ROW_EXPORT_FAILURE,
    TOPIC_TEAM_EXPORT_FAILURE,
    TOPIC_TEAM_ROW_EXPORT_FAILURE,
    CASE_DATA_DYNAMIC_ROW_EXPORT_FAILURE,
    DYNAMIC_EXPORT_FAILURE,
    DYNAMIC_ROW_EXPORT_FAILURE,
    SOMU_EXPORT_FAILURE,
    SOMU_ROW_EXPORT_FAILURE,
    INVALID_EXPORT_PERMISSION,
    CUSTOM_EXPORT_FAILURE,
    CUSTOM_ROW_EXPORT_FAILURE,
    REST_HELPER_GET_UNAUTHORIZED,
    REST_HELPER_GET_FORBIDDEN,
    REST_HELPER_GET_NOT_FOUND,
    REST_HELPER_GET_BAD_REQUEST,
    REST_HELPER_POST_FAILURE;

    public static final String EVENT = "event_id";
    public static final String EXCEPTION = "exception";

}
