apiVersion: batch/v1
kind: Job
metadata:
  name: hocs-update-materialized-views
  labels:
    role: hocs-update-materialized-views
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        name: hocs-update-materialized-views
        role: hocs-update-materialized-views
        database: required
    spec:
      containers:
        - name: hocs-update-materialized-views
          image: quay.io/ukhomeofficedigital/hocs-toolbox:1.7.1
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          command: [ "/bin/sh", "-c" ]
          args:
            - psql -tA -f sql/Audit-Schema-DataUpdates.sql
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: cs-qa-audit-rds
                  key: host
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: cs-qa-audit-rds
                  key: name
            - name: DB_SCHEMA_NAME
              valueFrom:
                secretKeyRef:
                  name: cs-qa-audit-rds
                  key: schema_name
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: cs-qa-audit-rds
                  key: user_name
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: cs-qa-audit-rds
                  key: password
      restartPolicy: Never
