apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hocs-refresh-dcu-caseview
spec:
  schedule: {{.REFRESH_CRON}}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            name: hocs-refresh-dcu-caseview
            role: hocs-backend
        spec:
          containers:
            - name: hocs-refresh-dcu-caseview
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
              image: quay.io/ukhomeofficedigital/hocs-base-image:latest
              env:
                - name: HOCS_BASICAUTH
                  valueFrom:
                    secretKeyRef:
                      name: ui-casework-creds
                      key: plaintext
              command: ["/bin/sh", "-c"]
              args:
                - http_status=$( wget --no-check-certificate --spider -S "https://${HOCS_BASICAUTH}@hocs-audit.{{.KUBE_NAMESPACE}}.svc.cluster.local/admin/export/custom/DCU_AGGREGATED_CASES/refresh" 2>&1 | grep "HTTP/" | awk '{print $2}' ); if [[ $http_status -eq 200 ]]; then exit 0; else exit 1; fi
          restartPolicy: Never
