---
kind: pipeline
type: kubernetes
name: deploy
trigger:
  event:
    - promote

steps:
  - name: fetch and checkout
    image: alpine/git
    commands:
      - git fetch --tags
      - git checkout $${VERSION}

  - name: deploy to cs-qa
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: cs-qa
      KUBE_TOKEN:
        from_secret: hocs_audit_cs_qa
    when:
      target:
        - release
    depends_on:
      - fetch and checkout

  - name: deploy to wcs-qa
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: wcs-qa
      KUBE_TOKEN:
        from_secret: hocs_audit_wcs_qa
    when:
      target:
        - release
    depends_on:
      - fetch and checkout

  - name: deploy to not prod
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: hocs_audit_${DRONE_DEPLOY_TO/-/_}
    depends_on:
      - fetch and checkout
    when:
      event:
        - promote
      target:
        exclude:
          - release
          - "*-prod"

  - name: deploy to prod
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: hocs_audit_${DRONE_DEPLOY_TO/-/_}
    depends_on:
      - fetch and checkout
    when:
      event:
        - promote
      target:
        include:
          - "*-prod"
---
kind: pipeline
type: kubernetes
name: deploy tag
trigger:
  event:
