---
kind: pipeline
type: kubernetes
name: build
trigger:
  event:
    - push
  branch:
    exclude:
      - main

services:
  - name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev

  - name: localstack
    image: localstack/localstack:0.14.3.1
    environment:
      SERVICES: sqs
      DEFAULT_REGION: eu-west-2

steps:
  - name: setup localstack
    image: quay.io/ukhomeofficedigital/localstack
    commands:
      - ./config/localstack/setup-queues.sh
    depends_on:
      - clone

  - name: test project
    image: quay.io/ukhomeofficedigital/hocs-base-image-build:1.0.5
    environment:
      DB_HOST: "postgres"
      LOCALSTACK_HOST: "localstack"
    commands:
      - ./gradlew clean build --no-daemon
    depends_on:
      - setup localstack

  - name: sonar scanner
    image: quay.io/ukhomeofficedigital/sonar-scanner
    commands:
      - sonar-scanner -Dsonar.projectVersion="$(git rev-parse --abbrev-ref HEAD)"
    depends_on:
      - test project

  - name: build & push
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-audit
      tags:
        - ${DRONE_COMMIT_SHA}
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    depends_on:
      - test project

---
kind: pipeline
type: kubernetes
name: deploy
trigger:
  event:
    - promote

steps:
  - name: fetch and checkout
    image: alpine/git
    commands:
      - git fetch --tags
      - git checkout $${VERSION}

  - name: deploy to cs-qa
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: cs-qa
      KUBE_TOKEN:
        from_secret: hocs_audit_cs_qa
    when:
      target:
        - release
    depends_on:
      - fetch and checkout

  - name: deploy to wcs-qa
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: wcs-qa
      KUBE_TOKEN:
        from_secret: hocs_audit_wcs_qa
    when:
      target:
        - release
    depends_on:
      - fetch and checkout

  - name: deploy to not prod
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: hocs_audit_${DRONE_DEPLOY_TO/-/_}
    depends_on:
      - fetch and checkout
    when:
      event:
        - promote
      target:
        exclude:
          - release
          - "*-prod"

  - name: deploy to prod
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: hocs_audit_${DRONE_DEPLOY_TO/-/_}
    depends_on:
      - fetch and checkout
    when:
      event:
        - promote
      target:
        include:
          - "*-prod"

---
kind: pipeline
type: kubernetes
name: build tag
trigger:
  event:
    - tag
  branch:
    - main
    - support/*

services:
  - name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev

  - name: localstack
    image: quay.io/ukhomeofficedigital/localstack
    environment:
      SERVICES: sqs
      DEFAULT_REGION: eu-west-2

steps:
  - name: setup localstack
    image: quay.io/ukhomeofficedigital/localstack
    commands:
      - ./config/localstack/setup-queues.sh
    depends_on:
      - clone

  - name: test project
    image: quay.io/ukhomeofficedigital/hocs-base-image-build:1.0.5
    environment:
      DB_HOST: "postgres"
      LOCALSTACK_HOST: "localstack"
    commands:
      - ./gradlew clean build --no-daemon
    depends_on:
      - setup localstack

  - name: build & push tag main
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-audit
      tags:
        - ${DRONE_TAG}
        - ${DRONE_COMMIT_SHA}
        - latest
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    depends_on:
      - test project
    when:
      branch:
        - main

  - name: build & push tag
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-audit
      tags:
        - ${DRONE_TAG}
        - ${DRONE_COMMIT_SHA}
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    depends_on:
      - test project
    when:
      branch:
        - support/*

---
kind: pipeline
type: kubernetes
name: deploy tag
trigger:
  event:
    - tag
  branch:
    - main
depends_on:
  - build tag

steps:
  - name: deploy to cs-dev
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: cs-dev
      KUBE_TOKEN:
        from_secret: hocs_audit_cs_dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      VERSION: "${DRONE_TAG}"
    depends_on:
      - clone

  - name: deploy to wcs-dev
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: wcs-dev
      KUBE_TOKEN:
        from_secret: hocs_audit_wcs_dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      VERSION: "${DRONE_TAG}"
    depends_on:
      - clone
