pipeline:

  build-project:
    image: quay.io/ukhomeofficedigital/openjdk8
    commands:
      - SPRING_PROFILES_ACTIVE='development, local, test'
      - SERVER_PORT='8080'
      - AUDIT_QUEUE_NAME='audit-queue'
      - AUDIT_QUEUE_DLQ_NAME='audit-queue-dlq'
      - export DB_HOST='postgres'
      - AWS_LOCAL_HOST='localstack'
      - ./gradlew build
    when:
      event: [push, pull_request, tag]

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.2
    when:
      event: [push, pull_request, tag]


  docker-build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t hocs-audit .
    when:
      branch: [master, refs/tags/*]
      event: [push, tag]

  install-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag hocs-audit quay.io/ukhomeofficedigital/hocs-audit:build-$${DRONE_BUILD_NUMBER}
      - docker tag hocs-audit quay.io/ukhomeofficedigital/hocs-audit:latest
      - docker push quay.io/ukhomeofficedigital/hocs-audit:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/hocs-audit:latest
    when:
      branch: master
      event: push

  docker-semver-tag:
    image: quay.io/ukhomeofficedigital/hocs-version-bot:build-25
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
      - DOCKER_API_VERSION=1.37
    secrets:
      - github_password
      - docker_password
      - git_password
    commands:
      - /app/hocs-deploy --version=$${SEMVER} --serviceGitToken=$${GIT_PASSWORD} --service=hocs-audit --gitToken=$${GITHUB_PASSWORD} --gitRepo="https://gitlab.digital.homeoffice.gov.uk/hocs/hocs-versions.git" --environment=qa --dockerRepository=quay.io/ukhomeofficedigital --sourceBuild=$${IMAGE_VERSION} --registryUser=ukhomeofficedigital+hocs --registryPassword=$${DOCKER_PASSWORD}
    when:
      event: deployment
      environment: qa

  clone-kube-project:
    image: plugins/git
    commands:
      - git clone https://github.com/UKHomeOffice/kube-hocs-audit.git
    when:
      event: [push, tag, deployment]

  deploy-to-cs-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      - DOMAIN=cs
      - KUBE_NAMESPACE=cs-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_audit_dev
    commands:
      - cd kube-hocs-audit
      - ./deploy.sh
    when:
      branch: master
      event: [push, tag]

  deploy-to-wcs-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      - DOMAIN=wcs
      - KUBE_NAMESPACE=wcs-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_audit_dev
    commands:
      - cd kube-hocs-audit
      - ./deploy.sh
    when:
      branch: master
      event: [push, tag]

  deployment:
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      - ENVIRONMENT=${DRONE_DEPLOY_TO}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_audit_dev
      - hocs_audit_demo
    commands:
      - cd kube-hocs-audit
      - ./deploy.sh
    when:
      event: deployment
      environment: [dev, demo]

  deploy-to-qa:
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      - ENVIRONMENT=qa
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_audit_qa
    commands:
      - source version.txt
      - echo $VERSION
      - cd kube-hocs-audit
      - ./deploy.sh
    when:
      event: deployment
      environment: qa

  deploy-to-prod:
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      - ENVIRONMENT=prod
      - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
    secrets:
      - hocs_audit_prod
    commands:
      - cd kube-hocs-audit
      - ./deploy.sh
    when:
      event: deployment
      environment: prod

services:
  postgres:
    image: quay.io/ukhomeofficedigital/postgres-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
