---
kind: pipeline
type: kubernetes
name: build

services:
  - name: postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev

  - name: localstack
    image: quay.io/ukhomeofficedigital/localstack
    environment:
      SERVICES: sqs
      DEFAULT_REGION: eu-west-2

steps:
  - name: setup localstack
    image: quay.io/ukhomeofficedigital/localstack
    commands:
      - ./config/localstack/setup-queues.sh
    depends_on:
      - clone

  - name: build project
    image: quay.io/ukhomeofficedigital/hocs-base-image-build
    commands:
      - ./gradlew assemble --no-daemon
    depends_on:
      - setup localstack

  - name: test project
    image: quay.io/ukhomeofficedigital/hocs-base-image-build
    environment:
      DB_HOST: "postgres"
      LOCALSTACK_HOST: "localstack"
    commands:
      - ./gradlew check --no-daemon
    depends_on:
      - build project

  - name: sonar scanner
    image: quay.io/ukhomeofficedigital/sonar-scanner:v4.6
    commands:
      - sonar-scanner -Dsonar.projectVersion="$(git rev-parse --abbrev-ref HEAD)"
    depends_on:
      - test project

  - name: build & push branch
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-audit
      tags:
        - ${DRONE_COMMIT_SHA}
        - branch-${DRONE_COMMIT_BRANCH/\//_}
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    when:
      branch:
        exclude:
          - main
          - "dependabot*"
    depends_on:
      - test project

  - name: build & push main
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-audit
      tags:
        - ${DRONE_COMMIT_SHA}
        - latest
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    when:
      branch:
        - main
    depends_on:
      - test project

trigger:
  event:
    - push

---
kind: pipeline
type: kubernetes
name: deploy
depends_on:
  - build
trigger:
  event:
    exclude:
      - pull_request
      - tag

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

environment:
  DOCKER_HOST: tcp://docker:2375

steps:
  - name: fetch and checkout
    image: alpine/git
    commands:
      - git fetch --tags
      - git checkout $${VERSION}

  - name: deploy to cs-dev
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: cs-dev
      KUBE_TOKEN:
        from_secret: hocs_audit_cs_dev
      VERSION: "${DRONE_COMMIT_SHA}"
    depends_on:
      - fetch and checkout
    when:
      branch:
        - main
      event:
        - push

  - name: deploy to wcs-dev
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: wcs-dev
      KUBE_TOKEN:
        from_secret: hocs_audit_wcs_dev
      VERSION: "${DRONE_COMMIT_SHA}"
    depends_on:
      - fetch and checkout
    when:
      branch:
        - main
      event:
        - push

  - name: wait for docker
    image: docker
    commands:
      - n=0; until docker stats --no-stream; do echo "Waiting for Docker $n"; n=$((n +1)); sleep 1; done
    when:
      event:
        - promote
      target:
        - release

  - name: generate & tag build
    image: quay.io/ukhomeofficedigital/hocs-version-bot
    commands:
      - >
        /app/hocs-deploy
        --dockerRepository=quay.io/ukhomeofficedigital
        --environment=qa
        --registryPassword=$${DOCKER_PASSWORD}
        --registryUser=ukhomeofficedigital+hocs_quay_robot
        --service=hocs-audit
        --serviceGitToken=$${GITHUB_TOKEN}
        --sourceBuild=$${VERSION}
        --version=$${SEMVER}
        --versionRepo="https://gitlab.digital.homeoffice.gov.uk/hocs/hocs-versions.git"
        --versionRepoServiceToken=$${GITLAB_TOKEN}
    environment:
      DOCKER_API_VERSION: 1.40
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      GITLAB_TOKEN:
        from_secret: GITLAB_TOKEN
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    depends_on:
      - wait for docker
      - fetch and checkout
    when:
      event:
        - promote
      target:
        - release

  - name: deploy to cs-qa
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - source version.txt
      - echo $VERSION
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: cs-qa
      KUBE_TOKEN:
        from_secret: hocs_audit_cs_qa
    when:
      event:
        - promote
      target:
        - release
    depends_on:
      - generate & tag build

  - name: deploy to wcs-qa
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - source version.txt
      - echo $VERSION
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: wcs-qa
      KUBE_TOKEN:
        from_secret: hocs_audit_wcs_qa
    when:
      event:
        - promote
      target:
        - release
    depends_on:
      - generate & tag build

  - name: deploy to not prod
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: hocs_audit_${DRONE_DEPLOY_TO/-/_}
    depends_on:
      - fetch and checkout
    when:
      event:
        - promote
      target:
        exclude:
          - release
          - "*-prod"

  - name: deploy to prod
    image: quay.io/ukhomeofficedigital/kd
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: hocs_audit_${DRONE_DEPLOY_TO/-/_}
    depends_on:
      - fetch and checkout
    when:
      event:
        - promote
      target:
        include:
          - "*-prod"
