version: '3.8'

services:

  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - "5432:5432"
    networks:
      - hocs-network
    environment:
     POSTGRES_USER: root
     POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

  localstack:
    image: localstack/localstack:0.11.1
    ports:
      - "4566:4566"
    networks:
      - hocs-network
    environment:
      HOSTNAME_EXTERNAL: localstack
      DEFAULT_REGION: eu-west-2
      SERVICES: sqs

networks:
  hocs-network:
