localstack:
  host: localhost

aws:
  sqs:
    config:
      port: 4566
      url: http://${localstack.host}:${aws.sqs.config.port}
    audit:
      url: ${aws.sqs.config.url}/queue/${aws.queue.audit.name}

postgresViewAllowList: allow1,allow2
