aws:
  sqs:
    config:
      host: localhost
      port: 4566
      url: http://${aws.sqs.config.host}:${aws.sqs.config.port}
    audit:
      url: ${aws.sqs.config.url}/queue/${aws.queue.audit.name}

spring:
  datasource:
    url: jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.name:postgres}?currentSchema=${db.schema.name:audit}&user=${db.username:root}&password=${db.password:dev}&stringtype=unspecified
  flyway:
    schemas: ${db.schema.name:audit}
