aws:
  sqs:
    audit:
      name: audit-queue
      access.key: 12345
      secret.key: 12345
      region: eu-west-2
      endpoint: http://localhost:4566
      url: ${aws.sqs.audit.endpoint}/queue/${aws.sqs.audit.name}