localstack:
  host: localhost

aws:
  sqs:
    config:
      port: 4566
      url: http://${localstack.host}:${aws.sqs.config.port}
    audit:
      url: ${aws.sqs.config.url}/000000000000/${aws.queue.audit.name}
    audit-dlq:
      name: audit-queue-dlq
      url: ${aws.sqs.config.url}/000000000000/${aws.sqs.audit-dlq.name}


postgresViewAllowList: allow1,allow2
