info:
    app:
        fullname: Hocs Audit Service
        name: ${name:hocs-audit-service}
        version: ${version:0.0.1}

server:
    max-http-header-size: 1048576
    port: 8087
    shutdown: graceful

spring:
    main:
        banner-mode: off
    cache:
        caffeine:
            spec: initialCapacity=500,expireAfterWrite=600s
    datasource:
        url: jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.name:postgres}?currentSchema=${db.schema.name:audit}&user=${db.username:root}&password=${db.password:dev}&stringtype=unspecified
    flyway:
        locations: classpath:/db/migration/postgresql
        schemas: ${db.schema.name:audit}

hocs:
    basicauth: UNSET
    case-service: http://localhost:8082
    info-service: http://localhost:8085

postgresViewAllowList: dcu_aggregated_cases,dcu_business,dcu_prau_workflow
