
--- monthly
CREATE TABLE audit_event_2023_1 PARTITION OF audit_event
    FOR VALUES FROM ('2023-01-01') TO ('2023-02-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2023_1_viewed PARTITION OF audit_event_2023_1
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2023_1_default PARTITION OF audit_event_2023_1
    DEFAULT;

---
CREATE TABLE audit_event_2023_2 PARTITION OF audit_event
    FOR VALUES FROM ('2023-02-01') TO ('2023-03-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2023_2_viewed PARTITION OF audit_event_2023_2
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2023_2_default PARTITION OF audit_event_2023_2
    DEFAULT;

---
CREATE TABLE audit_event_2023_3 PARTITION OF audit_event
    FOR VALUES FROM ('2023-03-01') TO ('2023-04-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2023_3_viewed PARTITION OF audit_event_2023_3
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2023_3_default PARTITION OF audit_event_2023_3
    DEFAULT;

---
CREATE TABLE audit_event_2023_4 PARTITION OF audit_event
    FOR VALUES FROM ('2023-04-01') TO ('2023-05-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2023_4_viewed PARTITION OF audit_event_2023_4
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2023_4_default PARTITION OF audit_event_2023_4
    DEFAULT;

---
CREATE TABLE audit_event_2023_5 PARTITION OF audit_event
    FOR VALUES FROM ('2023-05-01') TO ('2023-06-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2023_5_viewed PARTITION OF audit_event_2023_5
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2023_5_default PARTITION OF audit_event_2023_5
    DEFAULT;

---
CREATE TABLE audit_event_2023_6 PARTITION OF audit_event
    FOR VALUES FROM ('2023-06-01') TO ('2023-07-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2023_6_viewed PARTITION OF audit_event_2023_6
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2023_6_default PARTITION OF audit_event_2023_6
    DEFAULT;

---

CREATE TABLE audit_event_2023_7 PARTITION OF audit_event
    FOR VALUES FROM ('2023-07-01') TO ('2023-08-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2023_7_viewed PARTITION OF audit_event_2023_7
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2023_7_default PARTITION OF audit_event_2023_7
    DEFAULT;

---

CREATE TABLE audit_event_2023_8 PARTITION OF audit_event
    FOR VALUES FROM ('2023-08-01') TO ('2023-09-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2023_8_viewed PARTITION OF audit_event_2023_8
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2023_8_default PARTITION OF audit_event_2023_8
    DEFAULT;

---

CREATE TABLE audit_event_2023_9 PARTITION OF audit_event
    FOR VALUES FROM ('2023-09-01') TO ('2023-10-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2023_9_viewed PARTITION OF audit_event_2023_9
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2023_9_default PARTITION OF audit_event_2023_9
    DEFAULT;

---

CREATE TABLE audit_event_2023_10 PARTITION OF audit_event
    FOR VALUES FROM ('2023-10-01') TO ('2023-11-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2023_10_viewed PARTITION OF audit_event_2023_10
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2023_10_default PARTITION OF audit_event_2023_10
    DEFAULT;

---

CREATE TABLE audit_event_2023_11 PARTITION OF audit_event
    FOR VALUES FROM ('2023-11-01') TO ('2023-12-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2023_11_viewed PARTITION OF audit_event_2023_11
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2023_11_default PARTITION OF audit_event_2023_11
    DEFAULT;

---

CREATE TABLE audit_event_2023_12 PARTITION OF audit_event
    FOR VALUES FROM ('2023-12-01') TO ('2024-01-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2023_12_viewed PARTITION OF audit_event_2023_12
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2023_12_default PARTITION OF audit_event_2023_12
    DEFAULT;
