---
hocs-generic-service:
  nameOverride: hocs-audit

  deployment:
    annotations:
      downscaler/downtime: 'Mon-Sun 00:00-05:00 Europe/London,Mon-Sun 23:00-24:00 Europe/London'

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-audit
    resources:
      limits:
        cpu: 1000m
        memory: 1536Mi
      requests:
        cpu: 200m
        memory: 1536Mi
    env:
      javaOpts: >-
        -XX:InitialRAMPercentage=50 -XX:MaxRAMPercentage=70
        -Djava.security.egd=file:/dev/./urandom
        -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks
        -Dhttps.proxyHost=hocs-outbound-proxy.{{ .Release.Namespace }}.svc.cluster.local
        -Dhttps.proxyPort=31290
        -Dhttp.nonProxyHosts=*.{{ .Release.Namespace }}.svc.cluster.local
      springProfiles: 'sqs'
      infoService: https://hocs-info-service.{{ .Release.Namespace }}.svc.cluster.local
      caseService: https://hocs-casework.{{ .Release.Namespace }}.svc.cluster.local

  keycloak:
    enabled: true
    realm: https://sso.digital.homeoffice.gov.uk/auth/realms/hocs-prod
    timeout: 300
    domain: cs.homeoffice.gov.uk

cron:
  refresh: '30 5 * * *'
