package uk.gov.digital.ho.hocs.audit.application;

public enum LogEvent {

    AUDIT_EVENT_CREATED,
    AUDIT_RECORD_NOT_FOUND,
    AUDIT_STARTUP_FAILURE,
    INVALID_AUDIT_PAYLOAD_STORED,
    AUDIT_EVENT_CREATION_FAILED,
    UNCAUGHT_EXCEPTION,
    REST_HELPER_GET,
    INFO_CLIENT_GET_TEAMS_SUCCESS,
    INFO_CLIENT_GET_USERS_AND_TEAMS_SUCCESS,
    INFO_CLIENT_GET_ALL_TEAMS_SUCCESS,
    INFO_CLIENT_GET_TEAM_SUCCESS,
    INFO_CLIENT_GET_UNITS_SUCCESS,
    INFO_CLIENT_GET_CASE_TYPES_SUCCESS,
    INFO_CLIENT_GET_USERS_SUCCESS,
    INFO_CLIENT_GET_USER_SUCCESS,
    INFO_CLIENT_GET_EXPORT_FIELDS_SUCCESS,
    INFO_CLIENT_GET_EXPORT_VIEWS_SUCCESS,
    INFO_CLIENT_GET_EXPORT_VIEW_SUCCESS,
    INFO_CLIENT_GET_EXPORT_VIEW_FAILURE,
    INFO_CLIENT_GET_SOMUTYPE_SUCCESS,
    CSV_EXPORT_START,
    CSV_EXPORT_COMPETE,
    CSV_EXPORT_FAILURE,
    REFRESH_MATERIALISED_VIEW,
    CSV_CUSTOM_CONVERTER_FAILURE,
    INFO_CLIENT_GET_TOPIC_SUCCESS,
    CASEWORK_CLIENT_GET_CORRESPONDENTS_SUCCESS,
    CASEWORK_CLIENT_GET_CORRESPONDENTS_FAILURE,
    CASEWORK_CLIENT_GET_TOPICS_SUCCESS,
    CASEWORK_CLIENT_GET_TOPICS_FAILURE,
    CASEWORK_CLIENT_GET_CASE_REFERENCE_SUCCESS,
    CASEWORK_CLIENT_GET_CASE_REFERENCE_FAILURE;

    public static final String EVENT = "event_id";
    public static final String EXCEPTION = "exception";
}
