package uk.gov.digital.ho.hocs.audit.application;

public enum LogEvent {

    AUDIT_EVENT_CREATED,
    AUDIT_RECORD_NOT_FOUND,
    AUDIT_STARTUP_FAILURE,
    INVALID_AUDIT_PALOAD_STORED,
    AUDIT_EVENT_CREATION_FAILED,
    UNCAUGHT_EXCEPTION,
    REST_HELPER_GET,
    REST_HELPER_GET_UNAUTHORIZED,
    REST_HELPER_GET_FORBIDDEN,
    REST_HELPER_GET_NOT_FOUND,
    REST_HELPER_GET_BAD_REQUEST,
    INFO_CLIENT_GET_TEAMS_SUCCESS,
    INFO_CLIENT_GET_CASE_TYPES_SUCCESS,
    INFO_CLIENT_GET_CASE_TYPE_SHORT_SUCCESS,
    INFO_CLIENT_GET_CASE_TYPE_SUCCESS,
    INFO_CLIENT_GET_EXPORT_FIELDS_SUCCESS,
    CSV_EXPORT_START,
    CSV_EXPORT_COMPETE,
    CSV_EXPORT_FAILURE;

    public static final String EVENT = "event_id";
    public static final String EXCEPTION = "exception";
}
