
--- monthly
CREATE TABLE audit_event_2025_1 PARTITION OF audit_event
    FOR VALUES FROM ('2025-01-01') TO ('2025-02-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2025_1_viewed PARTITION OF audit_event_2025_1
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2025_1_default PARTITION OF audit_event_2025_1
    DEFAULT;

---
CREATE TABLE audit_event_2025_2 PARTITION OF audit_event
    FOR VALUES FROM ('2025-02-01') TO ('2025-03-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2025_2_viewed PARTITION OF audit_event_2025_2
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2025_2_default PARTITION OF audit_event_2025_2
    DEFAULT;

---
CREATE TABLE audit_event_2025_3 PARTITION OF audit_event
    FOR VALUES FROM ('2025-03-01') TO ('2025-04-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2025_3_viewed PARTITION OF audit_event_2025_3
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2025_3_default PARTITION OF audit_event_2025_3
    DEFAULT;

---
CREATE TABLE audit_event_2025_4 PARTITION OF audit_event
    FOR VALUES FROM ('2025-04-01') TO ('2025-05-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2025_4_viewed PARTITION OF audit_event_2025_4
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2025_4_default PARTITION OF audit_event_2025_4
    DEFAULT;

---
CREATE TABLE audit_event_2025_5 PARTITION OF audit_event
    FOR VALUES FROM ('2025-05-01') TO ('2025-06-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2025_5_viewed PARTITION OF audit_event_2025_5
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2025_5_default PARTITION OF audit_event_2025_5
    DEFAULT;

---
CREATE TABLE audit_event_2025_6 PARTITION OF audit_event
    FOR VALUES FROM ('2025-06-01') TO ('2025-07-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2025_6_viewed PARTITION OF audit_event_2025_6
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2025_6_default PARTITION OF audit_event_2025_6
    DEFAULT;

---

CREATE TABLE audit_event_2025_7 PARTITION OF audit_event
    FOR VALUES FROM ('2025-07-01') TO ('2025-08-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2025_7_viewed PARTITION OF audit_event_2025_7
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2025_7_default PARTITION OF audit_event_2025_7
    DEFAULT;

---

CREATE TABLE audit_event_2025_8 PARTITION OF audit_event
    FOR VALUES FROM ('2025-08-01') TO ('2025-09-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2025_8_viewed PARTITION OF audit_event_2025_8
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2025_8_default PARTITION OF audit_event_2025_8
    DEFAULT;

---

CREATE TABLE audit_event_2025_9 PARTITION OF audit_event
    FOR VALUES FROM ('2025-09-01') TO ('2025-10-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2025_9_viewed PARTITION OF audit_event_2025_9
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2025_9_default PARTITION OF audit_event_2025_9
    DEFAULT;

---

CREATE TABLE audit_event_2025_10 PARTITION OF audit_event
    FOR VALUES FROM ('2025-10-01') TO ('2025-11-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2025_10_viewed PARTITION OF audit_event_2025_10
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2025_10_default PARTITION OF audit_event_2025_10
    DEFAULT;

---

CREATE TABLE audit_event_2025_11 PARTITION OF audit_event
    FOR VALUES FROM ('2025-11-01') TO ('2025-12-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2025_11_viewed PARTITION OF audit_event_2025_11
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2025_11_default PARTITION OF audit_event_2025_11
    DEFAULT;

---

CREATE TABLE audit_event_2025_12 PARTITION OF audit_event
    FOR VALUES FROM ('2025-12-01') TO ('2026-01-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2025_12_viewed PARTITION OF audit_event_2025_12
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2025_12_default PARTITION OF audit_event_2025_12
    DEFAULT;
