
--- monthly
CREATE TABLE audit_event_2024_1 PARTITION OF audit_event
    FOR VALUES FROM ('2024-01-01') TO ('2024-02-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2024_1_viewed PARTITION OF audit_event_2024_1
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2024_1_default PARTITION OF audit_event_2024_1
    DEFAULT;

---
CREATE TABLE audit_event_2024_2 PARTITION OF audit_event
    FOR VALUES FROM ('2024-02-01') TO ('2024-03-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2024_2_viewed PARTITION OF audit_event_2024_2
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2024_2_default PARTITION OF audit_event_2024_2
    DEFAULT;

---
CREATE TABLE audit_event_2024_3 PARTITION OF audit_event
    FOR VALUES FROM ('2024-03-01') TO ('2024-04-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2024_3_viewed PARTITION OF audit_event_2024_3
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2024_3_default PARTITION OF audit_event_2024_3
    DEFAULT;

---
CREATE TABLE audit_event_2024_4 PARTITION OF audit_event
    FOR VALUES FROM ('2024-04-01') TO ('2024-05-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2024_4_viewed PARTITION OF audit_event_2024_4
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2024_4_default PARTITION OF audit_event_2024_4
    DEFAULT;

---
CREATE TABLE audit_event_2024_5 PARTITION OF audit_event
    FOR VALUES FROM ('2024-05-01') TO ('2024-06-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2024_5_viewed PARTITION OF audit_event_2024_5
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2024_5_default PARTITION OF audit_event_2024_5
    DEFAULT;

---
CREATE TABLE audit_event_2024_6 PARTITION OF audit_event
    FOR VALUES FROM ('2024-06-01') TO ('2024-07-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2024_6_viewed PARTITION OF audit_event_2024_6
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2024_6_default PARTITION OF audit_event_2024_6
    DEFAULT;

---

CREATE TABLE audit_event_2024_7 PARTITION OF audit_event
    FOR VALUES FROM ('2024-07-01') TO ('2024-08-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2024_7_viewed PARTITION OF audit_event_2024_7
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2024_7_default PARTITION OF audit_event_2024_7
    DEFAULT;

---

CREATE TABLE audit_event_2024_8 PARTITION OF audit_event
    FOR VALUES FROM ('2024-08-01') TO ('2024-09-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2024_8_viewed PARTITION OF audit_event_2024_8
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2024_8_default PARTITION OF audit_event_2024_8
    DEFAULT;

---

CREATE TABLE audit_event_2024_9 PARTITION OF audit_event
    FOR VALUES FROM ('2024-09-01') TO ('2024-10-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2024_9_viewed PARTITION OF audit_event_2024_9
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2024_9_default PARTITION OF audit_event_2024_9
    DEFAULT;

---

CREATE TABLE audit_event_2024_10 PARTITION OF audit_event
    FOR VALUES FROM ('2024-10-01') TO ('2024-11-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2024_10_viewed PARTITION OF audit_event_2024_10
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2024_10_default PARTITION OF audit_event_2024_10
    DEFAULT;

---

CREATE TABLE audit_event_2024_11 PARTITION OF audit_event
    FOR VALUES FROM ('2024-11-01') TO ('2024-12-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2024_11_viewed PARTITION OF audit_event_2024_11
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2024_11_default PARTITION OF audit_event_2024_11
    DEFAULT;

---

CREATE TABLE audit_event_2024_12 PARTITION OF audit_event
    FOR VALUES FROM ('2024-12-01') TO ('2025-01-01')
    PARTITION BY LIST(type);

CREATE TABLE audit_event_2024_12_viewed PARTITION OF audit_event_2024_12
    FOR VALUES IN ('CASE_SUMMARY_VIEWED','CASE_VIEWED','SOMU_ITEMS_VIEWED','SOMU_ITEM_VIEWED','STANDARD_LINE_VIEWED','TEMPLATE_VIEWED');

CREATE TABLE audit_event_2024_12_default PARTITION OF audit_event_2024_12
    DEFAULT;
