---
hocs-generic-service:

  deployment:
    annotations:
      downscaler/downtime: "Sat-Sun 00:00-24:00 Europe/London,Mon-Fri 00:00-07:55 Europe/London,Mon-Fri 18:05-24:00 Europe/London"

  clusterPrefix: cs

  keycloak:
    realm: https://sso-dev.notprod.homeoffice.gov.uk/auth/realms/hocs-notprod
    domain: cs-notprod.homeoffice.gov.uk

  app:
    resources:
      limits:
        memory: 768Mi
      requests:
        memory: 768Mi
