name: 'PR Checker'
on:
  pull_request:
    types: [ labeled, unlabeled, opened, reopened, synchronize ]

jobs:
  analyze:
    uses: UKHomeOffice/hocs-ci-infrastructure/.github/workflows/pr-check.yml@v1
