name: "Trivy Scan"

on:
  push:
    branches: [ main, 'hotfix/**' ]
  pull_request:
    types: [ labeled, opened, reopened, synchronize ]
  schedule:
    - cron: '45 12 * * 1'

jobs:
  scan:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/trivy-gradle.yml@3bfd60192418c462f7f86f0d79a6c8c26257ebe1
    with:
      severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      checkoutSubmodule: true
    secrets: inherit
